/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.pivotal.pal.tracker;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PalTrackerApplicationTest {
    @Test void appHasAGreeting() {
        PalTrackerApplication classUnderTest = new PalTrackerApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
