/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.pivotal.pal.tracker;

public class PalTrackerApplication {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new PalTrackerApplication().getGreeting());
    }
}
